apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-store
  template:
    metadata:
      labels:
        app: file-store
    spec:
      containers:
      - name: file-store
        image: python:3.9
        command: ["python3", "/app/server.py"]
        ports:
        - containerPort: 5000
